# permissions for end users to view tfjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tfjob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple-operator
    app.kubernetes.io/part-of: simple-operator
    app.kubernetes.io/managed-by: kustomize
  name: tfjob-viewer-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs/status
  verbs:
  - get
